services:
  vk-test-main-app:
    build:
      context: ./
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: vk-test-main-app
    restart: on-failure
    ports:
      - '3000:3000'
  mock-api:
    build:
      context: ./db
    container_name: vk-test-mock-api
    restart: on-failure
    ports:
      - '3001:3001'